AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  library-api

  A REST API for a library management service

Resources:
  GetBooksFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: dist/lambdas/get-books
      Runtime: go1.x
      Tracing: Active
      Events:
        GetEvent:
          Type: Api
          Properties:
            Path: /books
            Method: get
  GetBookByIDFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: dist/lambdas/get-book-by-id
      Runtime: go1.x
      Tracing: Active
      Events:
        GetEvent:
          Type: Api
          Properties:
            Path: /book/{book_id}
            Method: get
  CreateBookFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: dist/lambdas/create-book
      Runtime: go1.x
      Tracing: Active
      Events:
        GetEvent:
          Type: Api
          Properties:
            Path: /book
            Method: post
  UpdateBookFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: dist/lambdas/update-book
      Runtime: go1.x
      Tracing: Active
      Events:
        GetEvent:
          Type: Api
          Properties:
            Path: /book/{book_id}
            Method: put
  DeleteBookFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: dist/lambdas/delete-book
      Runtime: go1.x
      Tracing: Active
      Events:
        GetEvent:
          Type: Api
          Properties:
            Path: /book/{book_id}
            Method: delete

Outputs:
  Endpoint:
    Value:  !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/"